language: node_js
os: linux
node_js:
  - 14
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  keep_history: true
  on:
    branch: master
cache:
  directories:
    - node_modules
script:
  - npm run build
